### ISSUE TITLE
Create a requirements.txt file

### ISSUE THREAD

**Issue by kiranrokkam09** [ZoroZoro95/Blog-Site#14]
hey @ZoroZoro95 it's very difficult to work on the project without the requirements.txt file. I am facing many issues with the versions of django and python.

**Comment by Zubairahmdfaraz** [comment]
Believe me its easy. I hope you created a virtual environment at the start of project. When you installed packages/libraries required for the project , they all will be stored in the virtual env.  Just run  command`pip freeze > requirements.txt`.This command  will create a requirements.txt file and list all the dependencies/packages/libraries required .

**Comment by kiranrokkam09** [comment]
@Zubairahmdfaraz I also know how to create a requirements.txt file.but the problem is the version of python and django in my system does not fit with your project. your project should have the requirements.txt for the users to install the require versions of packages in virtual env.

**Comment by kiranrokkam09** [comment]
Not every user will create their own requirements.txt file. The author should provide the requirements.txt file to use their project in the virtual environment by the user.

**Comment by Zubairahmdfaraz** [comment]
Just run the code and  your interpretor will mention the requirements.
